version: "3.8"
services:
  weather-api:
    build: .
    container_name: weather_api
    ports:
      - "9090:8000"
    depends_on:
      - redis  
      - postgres 
    environment:
      REDIS_HOST: redis  
      REDIS_PORT: 6379
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env 
  redis:
    image: "redis:alpine"
    container_name: weather_redis
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:15"
    container_name: weather_postgres
    restart: always

    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

