version: "3.8"
services:
  weather-api:
    build: .
    container_name: weather_api
    ports:
      - "8080:8000"
    depends_on:
      - redis  
    environment:
      REDIS_HOST: redis  
      REDIS_PORT: 6379
    env_file:
      - .env 
  redis:
    image: "redis:alpine"
    container_name: weather_redis
    restart: always
    ports:
      - "6379:6379"


